{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ coalesce .Values.externalSecrets.name (include "nucleus.fullname" .) }}
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
  {{- $baseAnnotations := fromYaml (include "nucleus.annotations" .) }}
  {{- $annotations := mergeOverwrite $baseAnnotations .Values.externalSecrets.annotations }}
  {{- if $annotations }}
  annotations:
    {{- include "nucleus.formatAnnotations" $annotations | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: "{{ .Values.externalSecrets.refreshInterval | default 0 }}"
  {{- with .Values.externalSecrets.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.target }}
  target:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecrets.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}