{{- if and .Values.autoscaling.enabled (eq .Values.autoscaling.type "keda") }}
{{- if semverCompare "<1.23-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "nucleus.fullname" . }}
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
  {{- with fromYaml (include "nucleus.annotations" .) }}
  annotations:
    {{- include "nucleus.formatAnnotations" . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ include "nucleus.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  pollingInterval: {{ .Values.autoscaling.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.autoscaling.keda.cooldownPeriod | default 180 }}
  fallback:
    failureThreshold: 3
    replicas: {{ .Values.autoscaling.maxReplicas }}
  {{- with .Values.autoscaling.keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.autoscaling.keda.baseTriggers .Values.autoscaling.keda.additionalTriggers .Values.autoscaling.keda.triggers }}
  triggers:    
    {{- /* Base/Default triggers */}}
    {{- with .Values.autoscaling.keda.baseTriggers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- /* Additional triggers - controllable via enabled flag */}}
    {{- with .Values.autoscaling.keda.additionalTriggers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}