{{- range .Values.additionalSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "nucleus.labels" $ | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $baseAnnotations := fromYaml (include "nucleus.annotations" $) }}
  {{- $annotations := mergeOverwrite $baseAnnotations (.annotations | default dict) }}
  {{- if $annotations }}
  annotations:
    {{- include "nucleus.formatAnnotations" $annotations | nindent 4 }}
  {{- end }}
type: {{ .type | default "Opaque" }}
{{- if .data }}
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- else if .stringData }}
stringData:
  {{- toYaml .stringData | nindent 2 }}
{{- end }}
{{- end }}

