{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nucleus.serviceAccountName" . }}
  labels:
    {{- include "nucleus.labels" . | nindent 4 }}
  {{- with mergeOverwrite (fromYaml (include "nucleus.annotations" .)) .Values.serviceAccount.annotations }}
  annotations:
    {{- include "nucleus.formatAnnotations" . | nindent 4 }}
  {{- end }}
{{- end }}